"""Structural type for automation backends (Fake/Real share this shape)."""

from __future__ import annotations

from typing import Protocol

from humanoid_bot.automation.windows_info import WindowInfo


class AnyBackend(Protocol):
    def launch(self, exe: str, args: list[str]) -> None: ...
    def close_app(self, app: str) -> bool: ...
    def type_text(self, text: str) -> None: ...
    def press_key(self, key: str) -> None: ...
    def hotkey(self, keys: list[str]) -> None: ...
    def click(self, x: int, y: int, button: str = ...) -> None: ...
    def move_mouse(self, x: int, y: int) -> None: ...
    def find_windows(self, query: str = ...) -> list[WindowInfo]: ...
    def active_window(self) -> WindowInfo: ...
    def read_window(self, title: str) -> str: ...
